### ISSUE TITLE
Problem with create file GC_content.tab

### ISSUE THREAD

**Issue by Sondr11** [J35P312/AMYCNE#3]

**Comment by Sondr11** [comment]
can someone help me with problem?

**Comment by J35P312** [comment]
Hello!
We run it with bigger binsize (100 000):

Generate_GC_tab.py --fa hg19.fa --size 100000 

Remember to run TIDDIT with same binsize (i.e 100 kbp).

I recomend using older tiddit (like tiddit 2.12.0, which is on conda), newer tiddit does not include the quality column, and I rebuild AMYCNE FFY completele in the near future.

Try this, and tell me if you run into any problems!

**Comment by Sondr11** [comment]
Thank you very much. I will try run again.

**Comment by Sondr11** [comment]
Hi
I try again with binsize 100000, but I received error Killed on ternimal.
![IMG_20220915_192238_HDR](https://user-images.githubusercontent.com/113531212/190404967-e6d7f931-b1ba-40a4-aef0-910d2c6734b0.jpg)

**Comment by J35P312** [comment]
Though luck! Usually you get those errors due to low memory.
I see you are running virtualbox, I would give the machine at least 8 Gb ram.

No worries ;P.

**Comment by Sondr11** [comment]
Hì.
I have successfully predicted ff for male fetus.  But the results I got, the percentage of fetal DNA is much higher than other methods, about 7%.  With this high rate, I'm afraid to ignore low ff cases.  because, the rate of ff to return results is at least 4%.  Can you suggest me how to optimize?
Thank you

**Comment by J35P312** [comment]
Hello!
Do you have any male trisomy 21 samples? I usually use those for reference when fine tuning (i.e the FFY should correlate well to the WisecondorX 21 ratio). I suggest using 10 such samples.

There is a couple of parameters:

--intercept (the intercept is added to your FFY value)
--scaling (scaling, the slope of the line, multiplied to your FFY)

FFY'=(intercept)+(scaling)*FFY

where FFY is the value without adjustment (7% in your case), FFY' would be the value reported by AMYCNE if you change any of those parameters. If the estimate is to high, you probably need to set the scaling < 1 and intercept < 0.

Except for those two, you may also need to test different binsizes, and mapping quality thresholds (--Q). I use mapping quality threshold 30 on our 2*51bp reads

**Comment by Sondr11** [comment]
Hi
I used 1*50bp read. I will try again run according to your instructions.
Thank you
